# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mona/proto/rollout.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'mona/proto/rollout.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18mona/proto/rollout.proto\x12\x04mona\"\xda\x01\n\x07Rollout\x12\x15\n\rinitial_state\x18\x01 \x01(\x05\x12H\n\x17steps_to_box_milestones\x18\x02 \x03(\x0b\x32\'.mona.Rollout.StepsToBoxMilestonesEntry\x12\x19\n\x11num_boxes_in_hole\x18\x03 \x01(\x05\x12\x16\n\ntrajectory\x18\x04 \x03(\x05\x42\x02\x10\x01\x1a;\n\x19StepsToBoxMilestonesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\xc7\x01\n\x0cRolloutStats\x12\x1a\n\x12num_initial_states\x18\x01 \x01(\x05\x12\x1d\n\x15\x61verage_boxes_in_hole\x18\x02 \x01(\x02\x12\x37\n\x0e\x62ox_milestones\x18\x03 \x03(\x0b\x32\x1f.mona.RolloutStats.BoxMilestone\x1a\x43\n\x0c\x42oxMilestone\x12\x1a\n\x12num_initial_states\x18\x01 \x01(\x05\x12\x17\n\x0bstep_counts\x18\x02 \x03(\x05\x42\x02\x10\x01\"V\n\x10RolloutIteration\x12\x1f\n\x08rollouts\x18\x01 \x03(\x0b\x32\r.mona.Rollout\x12!\n\x05stats\x18\x02 \x01(\x0b\x32\x12.mona.RolloutStats\"?\n\x11RolloutIterations\x12*\n\niterations\x18\x01 \x03(\x0b\x32\x16.mona.RolloutIteration')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mona.proto.rollout_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROLLOUT_STEPSTOBOXMILESTONESENTRY']._loaded_options = None
  _globals['_ROLLOUT_STEPSTOBOXMILESTONESENTRY']._serialized_options = b'8\001'
  _globals['_ROLLOUT'].fields_by_name['trajectory']._loaded_options = None
  _globals['_ROLLOUT'].fields_by_name['trajectory']._serialized_options = b'\020\001'
  _globals['_ROLLOUTSTATS_BOXMILESTONE'].fields_by_name['step_counts']._loaded_options = None
  _globals['_ROLLOUTSTATS_BOXMILESTONE'].fields_by_name['step_counts']._serialized_options = b'\020\001'
  _globals['_ROLLOUT']._serialized_start=35
  _globals['_ROLLOUT']._serialized_end=253
  _globals['_ROLLOUT_STEPSTOBOXMILESTONESENTRY']._serialized_start=194
  _globals['_ROLLOUT_STEPSTOBOXMILESTONESENTRY']._serialized_end=253
  _globals['_ROLLOUTSTATS']._serialized_start=256
  _globals['_ROLLOUTSTATS']._serialized_end=455
  _globals['_ROLLOUTSTATS_BOXMILESTONE']._serialized_start=388
  _globals['_ROLLOUTSTATS_BOXMILESTONE']._serialized_end=455
  _globals['_ROLLOUTITERATION']._serialized_start=457
  _globals['_ROLLOUTITERATION']._serialized_end=543
  _globals['_ROLLOUTITERATIONS']._serialized_start=545
  _globals['_ROLLOUTITERATIONS']._serialized_end=608
# @@protoc_insertion_point(module_scope)
